POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento de um participante",
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/1fdf82ed-5e92-49dd-93a1-cbfe5185afd5/attendees
Content-Type: application/json

{
  "name": "Gabriel Pedro Ramalho",
  "email": "gabriel3@email.com"
}

###


GET http://localhost:3333/events/1fdf82ed-5e92-49dd-93a1-cbfe5185afd5


###

GET http://localhost:3333/attendees/3/badge

###

GET http://localhost:3333/attendees/3/check-in